<a href="https://colab.research.google.com/github/neelkrishna/tf-fundamentals/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lecture 0 - fundamental concepts of TF

* Intro to tensors
* Getting info from tensors
* Manipulating Tensors
* Tensors & NumPy
* Using @tf.function
* GPUs with TF
* Exercises

In [2]:
import tensorflow as tf
print (tf.__version__)

2.12.0


In [3]:
# Create scalar

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check tensor dimensions
scalar.ndim

0

In [6]:
# Create a vector

vector = tf.constant([10, 10])
vector
vector.ndim

1

In [8]:
# Create a matrix

matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix.ndim

2

In [11]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [17]:
# Let's create a tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                      [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor.ndim

3